apiVersion: v1
kind: Pod
metadata:
  name: little-help-book-dev
  labels:
    name: little-help-book-dev
spec:
  containers:
  - name: little-help-book-dev
    image: mvpstudio/little-help-book:Aug8
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
