apiVersion: v1
kind: Service
metadata:
  name: little-help-book-web
spec:
  type: NodePort
  selector:
    app: little-help-book
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
      targetPort: 8080
