apiVersion: apps/v1
kind: Deployment
metadata:
  name: little-help-book-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: little-help-book
  template:
    metadata:
      labels:
        app: little-help-book
    spec:
      containers:
        - name: web-server
          image: mvpstudio/little-help-book:Aug8
          resources:
            limits:
              cpu: 0.5
              memory: 500Mi
            requests:
              cpu: 0.5
              memory: 500Mi
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
