apiVersion: v1
kind: Service
metadata:
  name: little-help-book-web
  namespace: little-help-book-stage
spec:
  selector:
    app: little-help-book
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
